goodblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'', include('goodblogger.urls', namespace="blog"))
]

goodblogger/urls.py
"""Defines URL patterns for the goodblogger app"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # Home
    url(r'^$', views.index, name='index'),

    # All Topics
    url(r'^topics/$', views.topics, name='topics'),
    # Topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # New Topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # New Post
    url(r'^new_post/(?P<topic_id>\d+)/$', views.new_post, name='new_post'),
    # Edit Post
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post')
]

users/urls.py
"""Defines URL patterns for the usersystem"""

from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # Login Page
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    # Logout Page
    url(r'^logout/$', views.logout_view, name='logout'),
    # Registration Page
    url(r'^register/$', views.register, name='register'),
]

goodblogger/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic that a blog post can have"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """How to represent an instance as a string"""
        return self.text

class Post(models.Model):
    """A post in the blog"""
    topic = models.ForeignKey(Topic)
    title = models.CharField(max_length=128)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """How to represent an instance as a string"""
        return self.title

users/models.py
from django.db import models

# Create your models here.

goodblogger/forms.py
from django import forms

from .models import Topic, Post

class TopicForm(forms.ModelForm):
    """Form for Topics"""
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class PostForm(forms.ModelForm):
    """Form for Posts"""
    class Meta:
        model = Post
        fields = ['title', 'text']
        labels = { 'title': 'Title', 'text': 'Content' }
        widgets = { 'text': forms.Textarea(attrs={ 'cols': 80 }) }

goodblogger/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Post
from .forms import TopicForm, PostForm

# Create your views here.
def index(request):
    return render(request, 'goodblogger/index.html')

@login_required
def topics(request):
    """Show all of the user's topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    return render(request, 'goodblogger/topics.html', {'topics': topics})

@login_required
def topic(request, topic_id):
    """Displays a single topic and its posts"""
    topic = Topic.objects.get(id=topic_id)
    # Raise a 404 if the user doesn't own this topic
    if topic.owner != request.user:
        raise Http404
    posts = topic.post_set.order_by('-date_added')
    context = {'topic': topic, 'posts': posts}
    return render(request, 'goodblogger/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic"""
    if request.method != 'POST':
        # Display the blank form if data is not POSTed
        form = TopicForm()
    else:
        # Utilize POST data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('blog:topics'))
    return render(request, 'goodblogger/new_topic.html', {'form': form})

@login_required
def new_post(request, topic_id):
    """Add a new post"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # Display the blank form if data is not POSTed
        form = PostForm()
    else:
        # Utilize POST data
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('blog:topic', args=[topic_id]))
    context = { 'topic': topic, 'form': form }
    return render(request, 'goodblogger/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """Edit an existing post"""
    post = Post.objects.get(id=post_id)
    topic = post.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Prepares the form with the instance's existing data
        form = PostForm(instance=post)
    else:
        # Accept data and make changes
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:topic', args=[topic.id]))
    context = { 'post': post, 'topic': topic, 'form': form }
    return render(request, 'goodblogger/edit_post.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """Log a user out"""
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))

def register(request):
    """Registers a new user"""
    if request.method != 'POST':
        # Displays blank registration form
        form = UserCreationForm()
    else:
        # Process the completed form
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log user in and redirect to home
            auth_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, auth_user)
            return HttpResponseRedirect(reverse('blog:index'))
    return render(request, 'users/register.html', { 'form': form })

goodblogger/templates/goodblogger/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Goodblogger</title>

    {% bootstrap_css %}
    {% bootstrap_javascript%}
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class='container'>
        <div class='navbar-header'>
          <button type='button' class='navbar-toggle collapsed'
            data-toggle="collapse" data-target='#navbar'
            aria-expanded='false' aria-controls='navbar'></button>
          <a class='navbar-brand' href="{% url 'blog:index'%}">Goodblogger</a>
        </div>

        <div id='navbar' class='navbar-collapse collapse'>
          <ul class='nav navbar-nav'>
            <li><a href="{% url 'blog:topics' %}">Topics</a></li>
          </ul>

          <ul class='nav navbar-nav navbar-right'>
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}</a></li>
              <li><a href="{% url 'users:logout' %}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">Log In</a></li>
              <li><a href="{% url 'users:register' %}">Register</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class='page-header'>
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
    
  </body>
</html>

goodblogger/templates/goodblogger/edit_post.html
{% extends 'goodblogger/base.html' %}

{% block content %}
  <h2>New Post</h2>
  <h3>Topic: <a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></h3>

  <form action="{% url 'blog:edit_post' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save Changes</button>
  </form>
{% endblock content %}

goodblogger/templates/goodblogger/index.html
{% extends "goodblogger/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Just Post</h1>
  </div>
{% endblock header %}
{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register</a> now to start making really
    bad posts on-line.
  </h2>
  <h3>
    Only you can see your posts, because they are woefully unfit for public consumption.
  </h3>
{% endblock content %}

goodblogger/templates/goodblogger/new_post.html
{% extends 'goodblogger/base.html' %}

{% block content %}
  <h2>New Post</h2>
  <h3>Topic: <a href="{% url 'blog:topic' topic.id %}">{{ topic }}</a></h3>

  <form action="{% url 'blog:new_post' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Post</button>
  </form>
{% endblock content %}

goodblogger/templates/goodblogger/new_topic.html
{% extends 'goodblogger/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add New Topic</h2>
{% endblock header %}

{% block content %}
  <h2>New Topic</h2>
  <form action="{% url 'blog:new_topic' %}" method='post' class='form'>
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add Topic</button>
    {% endbuttons %}
  </form>
{% endblock content %}

goodblogger/templates/goodblogger/topic.html
{% extends 'goodblogger/base.html' %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <h3><a href="{% url 'blog:new_post' topic.id %}">New Post</a></h3>
  <h3>Posts:</h3>
  {% for post in posts %}
    <div class='panel panel-default'>
      <div class='panel-heading'>
        <h3>{{ post.title }}</h4>
        <h4>{{ post.date_added|date:'M d, Y H:i' }}</h3>
        <small>
          <a href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
        </small>
      </div>
      <div class='panel-body'>
        <p>{{ post.text }}</p>
      </div>
    </div>
  {% empty %}
    There are no posts for this topic.
  {% endfor %}
{% endblock content %}

goodblogger/templates/goodblogger/topics.html
{% extends "goodblogger/base.html" %}

{% block header %}
  <h2>Topics</h2>
{% endblock header %}

{% block content %}
<h3>
  <a href="{% url 'blog:new_topic' %}">Add New Topic</a>
</h3>
<ul>
  {% for topic in topics %}
    <li>
      <h3>
        <a href="{% url 'blog:topic' topic.id %}" >{{ topic }}</a>
      </h3>
    </li>
  {% empty %}
    <li>No topics added yet.</li>
  {% endfor %}
</ul>
{% endblock content %}

users/templates/users/login.html
{% extends "goodblogger/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log In to the On Line</h2>
{% endblock header %}

{% block content %}
  <form method='post' action="{% url 'users:login' %}" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log In</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blog:index' %}" />
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends "goodblogger/base.html" %}

{% block content %}

<form method='post' action="{% url 'users:register' %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit">Register</button>
  <input type="hidden" name="next" value="{% url 'blog:index' %}" />
</form>

{% endblock content %}